//
// Created by Michael Peng on 4/25/18.
//

#ifndef CSIM6502_STORAGE_HH
#define CSIM6502_STORAGE_HH

#include "../CPU.hh"
#include "Executor.hh"

namespace opcode {

NILADIC_OPCODE(CLC);
NILADIC_OPCODE(SEC);
NILADIC_OPCODE(CLI);
NILADIC_OPCODE(SEI);
NILADIC_OPCODE(CLV);
NILADIC_OPCODE(CLD);
NILADIC_OPCODE(SED);

}

#endif //CSIM6502_STORAGE_HH
